### ISSUE TITLE
Add picklist values & formulas to SObjects fields 

### ISSUE THREAD

**Issue by dinhphieu** [SCWells72/IcApexDoc#13]
First of all, thanks for this excellent tool, Scott!

Is it possible to also include if a field is a picklist or a formula, then fetch the related picklist values and the formulas contained inside? That would be immensely helpful to see at first glance, like a data dictionary or how Salesforce Inspector works when you hover over a field to see the details in it

For example:
![image](https://github.com/SCWells72/IcApexDoc/assets/42538587/03fa52d4-86af-467b-b5e9-99a2fbb953f8)

**Comment by SCWells72** [comment]
Hi, @dinhphieu. I'm glad you're finding IcApexDoc useful! Thanks for the enhancement suggestion. That's actually something I already do now in Illuminated Cloud 2 (IC2), displaying pretty much all of the available metadata for SObject fields in the derived documentation, e.g.:

![image](https://github.com/SCWells72/IcApexDoc/assets/7671043/e2181183-4a6c-41b3-b950-bf2a7b333bd9)

IC2 has the benefit of the full metadata for those fields from the org whereas IcApexDoc only has what's available in the local `*.object` and `*.object-meta.xml`/`*.field-meta.xml` files, but the interesting stuff should be in those files already anyway. I'll look into enhancing the SObject/field metadata that gets rendered into doc.

And I really need to move this project to open source as promised...all those other distractions seem to have gotten in the way!

**Comment by dinhphieu** [comment]
Great to hear, @SCWells72

Do you have an ETA for when this project will be open-sourced or when this feature will be delivered? I would love to help regarding this part!

**Comment by SCWells72** [comment]
@dinhphieu I can't really give a concrete estimate on either, but I think that this enhancement request is likely to happen first. With the holiday season coming it, it may be a few weeks, but I'm hoping I can work in a new build of IcApexDoc with this and a few other small things before the New Year. As for open sourcing the project, I'd planned to have that done by now, so shame on me for not getting to it. That requires a bit more legwork, though, so I think I'll probably focus on that just after the New Year and try to get it out there for people to look at/help with as early in 2024 as possible.
