### ISSUE TITLE
Generating Docs with Namespace results in @see references being incorrect

### ISSUE THREAD

**Issue by friskychicken** [SCWells72/IcApexDoc#14]
- Please note the two screen shots below: one was generated with package namespace and the other not.
- The one without namespace correctly links to other generated classes.

<img width="989" alt="Screenshot 2024-01-26 at 11 18 59" src="https://github.com/SCWells72/IcApexDoc/assets/1647218/a8291064-0b47-4683-9e4d-fe154988554a">
<img width="940" alt="Screenshot 2024-01-26 at 11 18 01" src="https://github.com/SCWells72/IcApexDoc/assets/1647218/1508ab3d-dca7-4ea0-959f-6d067a27a453">

**Comment by SCWells72** [comment]
Delivered in [1.0.0.9](https://github.com/SCWells72/IcApexDoc/releases/tag/1.0.0.9).
