### ISSUE TITLE
A blank line should be allowed between the comment and the class definition

### ISSUE THREAD

**Issue by aidan-harding** [SCWells72/IcApexDoc#7]
If I write a class like this:

```
/**
 * @author aidan@nebulaconsulting.co.uk
 * @date 15/03/2023
 * @description My Class does things
 */

public with sharing class MyClass {

}
```

Then apexdoc doesn't pick up the description and other comments. But, if I remove the blank line between the comment and the class, it does work:

```
/**
 * @author aidan@nebulaconsulting.co.uk
 * @date 15/03/2023
 * @description My Class does things
 */
public with sharing class MyClass {

}
```

For methods, I wouldn't have a blank line between the comment and the body. But for classes, I like it, and it seems like it should be allowed.

**Comment by SCWells72** [comment]
I've committed fixes for this in both IcApexDoc and IC2 for inclusion in the next respective builds of each, hopefully this Thursday for both.

**Comment by SCWells72** [comment]
Delivered in [1.0.0.2](https://github.com/SCWells72/IcApexDoc/releases/tag/1.0.0.2).
